plugins = []
functionsDirectory = "C:\\Users\\lauth\\OneDrive\\Desktop\\r\\netlify\\src\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\lauth\\OneDrive\\Desktop\\r\\netlify"
publishOrigin = "default"
base = "C:\\Users\\lauth\\OneDrive\\Desktop\\r\\netlify"
node_bundler = "esbuild"
functions = "C:\\Users\\lauth\\OneDrive\\Desktop\\r\\netlify\\src\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]